# Generated by Django 3.2.4 on 2021-06-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dongi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('product', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='consumer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('User_id', models.CharField(max_length=50, verbose_name='consumer')),
                ('buy_id', models.CharField(max_length=50)),
            ],
        ),
    ]
