# Generated by Django 3.2.4 on 2021-06-25 15:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dongi', '0002_buy_consumer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
